//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Server.BBBGameMicroservice.BBBGameMicroservice"/> </summary
    public sealed class BBBGameMicroserviceClient : MicroserviceClient, Beamable.Common.IHaveServiceName
    {
        
        public BBBGameMicroserviceClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        public string ServiceName
        {
            get
            {
                return "BBBGameMicroservice";
            }
        }
        
        /// <summary>
        /// Call the StartTheBattle method on the BBBGameMicroservice microservice
        /// <see cref="Beamable.Server.BBBGameMicroservice.BBBGameMicroservice.StartTheBattle"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Server.BBBGameMicroservice.StartTheBattleResults> StartTheBattle(Beamable.Server.BBBGameMicroservice.Content.BossContentRef bossContentRef, int heroWeaponIndexMax)
        {
            object raw_bossContentRef = bossContentRef;
            object raw_heroWeaponIndexMax = heroWeaponIndexMax;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("bossContentRef", raw_bossContentRef);
            serializedFields.Add("heroWeaponIndexMax", raw_heroWeaponIndexMax);
            return this.Request<Beamable.Server.BBBGameMicroservice.StartTheBattleResults>("BBBGameMicroservice", "StartTheBattle", serializedFields);
        }
        
        /// <summary>
        /// Call the AttackTheBoss method on the BBBGameMicroservice microservice
        /// <see cref="Beamable.Server.BBBGameMicroservice.BBBGameMicroservice.AttackTheBoss"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Server.BBBGameMicroservice.AttackTheBossResults> AttackTheBoss(System.Collections.Generic.List<Beamable.Server.BBBGameMicroservice.Content.WeaponContentRef> weaponContentRefs)
        {
            object raw_weaponContentRefs = weaponContentRefs;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("weaponContentRefs", raw_weaponContentRefs);
            return this.Request<Beamable.Server.BBBGameMicroservice.AttackTheBossResults>("BBBGameMicroservice", "AttackTheBoss", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersBBBGameMicroserviceClient
    {
        
        [System.SerializableAttribute()]
        internal sealed class ParameterBeamable_Server_BBBGameMicroservice_Content_BossContentRef : MicroserviceClientDataWrapper<Beamable.Server.BBBGameMicroservice.Content.BossContentRef>
        {
        }
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_Int32 : MicroserviceClientDataWrapper<int>
        {
        }
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_Collections_Generic_List_Beamable_Server_BBBGameMicroservice_Content_WeaponContentRef : MicroserviceClientDataWrapper<System.Collections.Generic.List<Beamable.Server.BBBGameMicroservice.Content.WeaponContentRef>>
        {
        }
    }
    
    [BeamContextSystemAttribute()]
    public static class ExtensionsForBBBGameMicroserviceClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<BBBGameMicroserviceClient>();
        }
        
        public static BBBGameMicroserviceClient BBBGameMicroservice(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<BBBGameMicroserviceClient>();
        }
    }
}
